### ISSUE TITLE
{"message":"Invalid device token","code":40100} for P-GPS and Cell Geolocation tests

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/nrfcloud-location-services-tests-js#94]
Since yesterday the https://github.com/NordicSemiconductor/nrfcloud-location-services-tests-js started to get for P-GPS and Cell Geolocation tests. The A-GPS tests work. 

Note that I have not changed the service keys or anything else since yesterday.

**Comment by savvyintegrations** [comment]
https://github.com/nRFCloud/backend/pull/825
